[project]
name = "server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Thais Carolina Braga de Magalhães", email = "thaisbraga969@gmail.com" }
]
requires-python = ">=3.11"
dependencies = []

[project.scripts]
server = "server:main"

[build-system]
requires = ["uv_build>=0.12.19,<0.13.0"]
build-backend = "uv_build"
